### ISSUE TITLE
Cadastro Atleta

### ISSUE THREAD

**Issue by deividcosta** [XadrezSuico/XadrezSuico#13]
Retirar da página de cadastro do atleta as duas partes de inscrição.( Cadastrar atleta, e inserir atleta no torneio). Para ficar mais intuitivo e prevenir erros. É interessante que o cadastro seja feito na segunda tela direto, assim o sistema valida o nome do atleta e se está cadastrado continua com o preenchimento das informações, se não está cadastrado ai então direciona para o cadastro do atleta com todas as informações e ao finalizar retorna ao ponto anterior continuando na inscrição do atleta no torneio. Usar dois formulários em separado para Cadastro de novo enxadrista e inscrição.

**Comment by jppcel** [comment]
Bom, acredito que a reformulação da página sugerida já atende também o problema que está em #7 .
Vou dar uma analisada em como fazer isto.

**Comment by deividcosta** [comment]
É que esqueci de incluir na mesma solicitação, mas sim, dá para atender na
mesma.

Em ter, 30 de jul de 2019 13:25, João Paulo Polles <notifications@github.com>
escreveu:

**Comment by deividcosta** [comment]
Seria interessante o atleta ou professor começar a digitar e seu nome aparecer e se no final do digitar, quanto tentasse sair da label para ir a outro passo se não fosse cadastrado o sistema direcionasse para o cadastro.

**Comment by jppcel** [comment]
Apenas para documentação, efetuando esta também irá resolver o #14.

**Comment by jppcel** [comment]
Uma nova tela de inscrição pública foi criada, considerando os feedbacks.

Não foi possível inserir tudo o que foi solicitado, mas foi o que foi possível trabalhar na nova tela.
